server:
  port: 9090
spring:
  jpa:
    database: oracle
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//10.40.3.215:1521/orcl
    username: bowaymes
    password: Boway1qaz@WSX

  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml
  redis:
    host: 10.40.3.209
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 500
        min-idle: 0
        shutdown-timeout: 0
    timeout: 1000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

# 自定义配置应用于topic交换器
mq:
  config:
    #自定义交换器名称
    exchange: log.topic
    queue:
      #自定义error、info、all队列名称
      errorName: topic.error.log
      infoName: topic.info.log
      allName: topic.all.log
      #自定义error、info、all路由键的名称
      routingInfoKey: topic.info.routing.key
      routingErrorKey: topic.error.routing.key








#logging:
#  file:
#    path: logs/
#    name:  ${logging.file.path}springboot.log
#  level:
#    root: trace


