server:
  port: 9090
spring:
  jpa:
    database: oracle
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: xxxxxx
    username: xxxxx
    password: xxxxxx

  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml




#logging:
#  file:
#    path: logs/
#    name:  ${logging.file.path}springboot.log
#  level:
#    root: trace


